const assert = require('node:assert/strict')
const fs = require('node:fs')
const test = require('node:test')

const manifest = JSON.parse(fs.readFileSync('src/manifest.json', 'utf8'))
const detail = fs.readFileSync('src/pages/detail/detail.ux', 'utf8')
const home = fs.readFileSync('src/pages/trial-home/trial-home.ux', 'utf8')
const end = fs.readFileSync('src/pages/trial-end/trial-end.ux', 'utf8')
const settings = fs.readFileSync('src/pages/settings/settings.ux', 'utf8')
const about = fs.readFileSync('src/pages/about/about.ux', 'utf8')
const index = JSON.parse(fs.readFileSync('src/common/story/story-index.txt', 'utf8'))

test('ships only the trial navigation flow', () => {
  assert.equal(manifest.versionCode, 1)
  assert.equal(manifest.versionName, '1.2')
  assert.equal(new Set(manifest.features.map((feature) => feature.name)).has('system.folme'), false)
  assert.equal(manifest.router.entry, 'pages/trial-home')
  assert.deepEqual(manifest.pages, ['pages/trial-home', 'pages/trial-end', 'pages/detail', 'pages/settings', 'pages/about'])
  assert.match(home, />试玩版</)
  assert.match(detail, />试玩版</)
  assert.doesNotMatch(`${home}\n${detail}\n${end}`, /activation|license|激活/)
})

test('ends the trial at scene 315 with AstroBox and official QQ group entry points', () => {
  assert.match(detail, /sceneIndex >= 315\) return router\.replace\(\{ uri: 'pages\/trial-end' \}\)/)
  assert.match(end, /完整版前往AstroBox购买/)
  assert.match(end, /value="https:\/\/astrobox\.online\/"/)
  assert.match(end, /扫码了解AstroBox/)
  assert.match(end, /加入官方QQ群/)
  assert.match(end, /群内抽取Steam原作CDK/)
  assert.match(end, /群号 1105166284/)
  assert.match(end, /src="\/common\/qq-group-qrcode\.png"/)
  assert.ok(fs.existsSync('src/common/qq-group-qrcode.png'))
  assert.equal(fs.existsSync('src/common/qq-group-qrcode.jpg'), false)
  assert.match(end, />返回首页<\/text>/)
  assert.doesNotMatch(end, /试玩首页|exit-btn|exitApp/)
  assert.match(end, /uri: 'pages\/trial-home'/)
})

test('opens the purchase page from static home actions', () => {
  assert.match(home, /id="trial-purchase"[^>]*@click="openPurchase">购买完整版<\/text>/)
  assert.match(home, /id="trial-exit"[^>]*@click="exitApp">退出<\/text>/)
  assert.match(home, /motionStaticClass: 'motion-static'/)
  assert.doesNotMatch(home, /createPageMotion|TRIAL_INITIAL_STATE|playIntro|setTimeout\(|folme|delay:/)
  assert.equal(fs.existsSync('src/common/page-motion.js'), false)
  assert.match(home, /openPurchase\(\) \{ router\.push\(\{ uri: 'pages\/trial-end' \}\) \}/)
  assert.match(home, /\.exit-action[^}]*width: 144px[^}]*background-color: #ead1da[^}]*color: #722c4b/)
  assert.match(home, /\.home-panel \{[^}]*background-color: #f5e1e8;[^}]*border-radius: 14px 14px 0px 0px;/)
  assert.doesNotMatch(home, /\.home-panel \{[^}]*opacity:/)
})

test('shows settings and about content without intro animation', () => {
  assert.doesNotMatch(settings, /createPageMotion|motionStaticClass|translateY\(/)
  assert.doesNotMatch(about, /createPageMotion|motionStaticClass|translateY\(/)
})

test('keeps text reveal and background motion off the JavaScript animation loop', () => {
  assert.match(detail, /if \(!this\.canContinue\) return this\.finishTyping\(\)/)
  assert.match(detail, /this\.index = Math\.min\(this\.typingText\.length, Math\.max\(this\.index \+ 1, Math\.floor\(elapsed \/ speed\) \+ 1\)\)/)
  assert.match(detail, /this\.showText = this\.typingText\.slice\(0, this\.index\)/)
  assert.match(detail, /setTimeout\(\(\) => this\.zhuzi\(token\), 50\)/)
  assert.doesNotMatch(detail, /showText \+= this\.typingText\.charAt/)
  assert.doesNotMatch(detail, /import folme from '@system\.folme'|folme\./)
  assert.match(detail, /stopBackgroundMotion\(\)/)
  assert.match(detail, /<scroll id="bg-horizontal-scroll" scroll-x="true" scroll-y="false" bounces="false" class="background-scroll"/)
  assert.match(detail, /startHorizontalBackgroundMotion\(token\)/)
  assert.match(detail, /const travel = 308/)
  assert.match(detail, /this\.scrollBackground\('bg-horizontal-scroll', left, 0\)/)
  assert.match(detail, /setTimeout\(tick, 50\)/)
  assert.doesNotMatch(detail, /animation-duration|@keyframes|background-horizontal-motion/)
  assert.match(detail, /const travel = 8/)
  assert.match(detail, /startVerticalBackgroundMotion\(token\)/)
  assert.match(detail, /this\.scrollBackground\('bg-vertical-scroll', 0, top\)/)
  assert.match(detail, /startHorizontalBackgroundMotion\(token\)/)
  assert.match(detail, /<scroll id="bg-vertical-scroll" scroll-x="false" scroll-y="true"/)
})

test('matches the full version 10 Pro reader and page layouts', () => {
  assert.match(detail, /@media \(shape: rect\) \{[\s\S]*?\.page \{ width: 212px; height: 303px; \}/)
  assert.match(detail, /@media \(shape: rect\) \{[\s\S]*?\.background-scroll \{ width: 212px; height: 303px; \}/)
  assert.match(detail, /@media \(shape: rect\) \{[\s\S]*?\.dialogue-panel \{ top: 187px; width: 212px; height: 116px;/)
  assert.match(detail, /@media \(shape: rect\) \{[\s\S]*?\.trial-label \{ top: 169px;/)
  assert.match(home, /src="\/common\/home-pro\.png"/)
  assert.ok(fs.existsSync('src/common/home-pro.png'))
  assert.match(home, /@media \(shape: rect\) \{[\s\S]*?\.home-logo \{ top: 18px; left: 36px; width: 140px; height: 80px; \}/)
  assert.match(home, /@media \(shape: rect\) \{[\s\S]*?\.home-panel \{ top: 118px; width: 212px; height: 185px;/)
  for (const page of [end, settings, about]) assert.match(page, /@media \(shape: rect\) \{[\s\S]*?\.page \{ width: 212px; height: 303px; \}/)
})

test('contains only trial scenes and their image resources', () => {
  assert.equal(index.storyId, 'gal-master-trial')
  assert.equal(index.nodeCount, 315)
  assert.equal(index.endScene, 314)
  assert.equal(index.chunks.length, 3)
  assert.equal(fs.readdirSync('src/common/story/chunks').filter((file) => /^story-\d+\.txt$/.test(file)).length, 3)
  const scenes = index.chunks.flatMap((chunk) => JSON.parse(fs.readFileSync(`src${chunk.file}`, 'utf8')))
  const used = new Set()
  for (const scene of scenes) {
    for (const image of [scene.background, scene.sceneOverlay && scene.sceneOverlay.image, scene.topRightOverlay && scene.topRightOverlay.image, scene.centerOverlay && scene.centerOverlay.image, scene.cgImage && scene.cgImage.image]) if (image) used.add(image.split('/').at(-1))
    for (const character of scene.characters || []) if (character.image) used.add(character.image.split('/').at(-1))
  }
  const images = new Set(fs.readdirSync('src/common/images'))
  assert.deepEqual(images, used)
})
