const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const index = fs.readFileSync('src/pages/index/index.ux', 'utf8')
const detail = fs.readFileSync('src/pages/detail/detail.ux', 'utf8')

test('renders a static compact home dock', () => {
  assert.match(index, /\.page \{ width: 336px; height: 480px;[^}]*overflow: hidden;/)
  assert.match(index, /\.home-background \{[^}]*top: 0px;[^}]*left: 0px;[^}]*width: 336px;[^}]*height: 480px;/)
  assert.match(index, /id="home-bg" static class="home-background" src="\/common\/home\.png"><\/image>/)
  assert.doesNotMatch(index, /home-shade/)
  assert.match(index, /<image static class="home-logo" src="\/common\/logo\.png"><\/image>/)
  assert.doesNotMatch(index, /home-logo-backplate/)
  assert.match(index, /<div class="home-panel">/)
  assert.match(index, /<text class="resume-copy">\{\{resumeCopy\}\}<\/text>/)
  assert.match(index, /<text class="primary-action" @click="continueGame">\{\{primaryAction\}\}<\/text>/)
  assert.match(index, /<div class="secondary-row">/)
  assert.match(index, /<div class="action-row">/)
  assert.match(index, /<text class="exit-action" @click="exit">退出<\/text>/)
  assert.match(index, /\.home-logo \{[^}]*top: 56px;[^}]*left: 28px;[^}]*width: 280px;[^}]*height: 120px;/)
  assert.match(index, /\.home-panel \{[^}]*top: 240px;[^}]*left: 0px;[^}]*width: 336px;[^}]*height: 240px;/)
  assert.match(index, /\.primary-action \{[^}]*width: 276px;[^}]*height: 48px;/)
  assert.match(index, /\.primary-action \{[^}]*border-radius: 10px;/)
  assert.match(index, /\.secondary-row \{[^}]*width: 276px;/)
  assert.match(index, /\.secondary-action \{[^}]*width: 132px;[^}]*border-radius: 10px;/)
  assert.match(index, /\.action-row \{[^}]*width: 276px;/)
  assert.match(index, /\.compact-action \{[^}]*width: 132px;[^}]*border-radius: 10px;/)
  assert.match(index, /\.exit-action \{[^}]*width: 276px;[^}]*height: 40px;/)
  assert.match(index, /refreshAutoSave\(\)/)
  assert.match(index, /key: 'autoSave'/)
  assert.doesNotMatch(index, /key: 'recoveryData'/)
  assert.match(index, /continueGame\(\)/)
  assert.match(index, /openSaves\(\)/)
  assert.match(index, /openSettings\(\)/)
  assert.match(index, /openAbout\(\)/)
  assert.doesNotMatch(index, /import folme|HOME_MOTION_IDS|HOME_INITIAL_STATE|HOME_FINAL_STATE|homeIntroToken|playHomeIntro|scheduleHomeMotion|runHomeMotion|setHomeInitialState|cancelHomeIntro/)
  assert.doesNotMatch(index, /homeStaticClass|home-static/)
  assert.doesNotMatch(index, /border-radius:\s*\d+px\s+\d+px/)
  assert.match(index, /\.home-panel \{[^}]*opacity: 0\.78;/)
  assert.doesNotMatch(index, /transform\s*:/)
  assert.doesNotMatch(index, /setTimeout\(|clearTimeout\(/)
  assert.doesNotMatch(index, /@keyframes|animation-name|animation-duration|animation-delay|animation-fill-mode|scaleX|scaleY|rotate/)
})

test('keeps the reader layers and makes dialogue readable above a dark panel', () => {
  const template = detail.slice(0, detail.indexOf('</template>'))
  const horizontalBackground = template.match(/<scroll id="bg-horizontal-scroll"[^>]*>/)[0]
  const verticalBackground = template.match(/<scroll id="bg-vertical-scroll"[^>]*>/)[0]
  const staticBackground = template.match(/<image id="bg-static"[^>]*>/)[0]
  const cgScroll = template.match(/<scroll id="cg-scroll"[^>]*>/)[0]

  assert.doesNotMatch(template, /class="reader-status"/)
  assert.match(template, /<div class="dialogue-panel" if="\{\{dialogueVisible(?: && !isUIHidden)?\}\}"/)
  assert.doesNotMatch(template, /class="text-bg"/)
  for (const background of [horizontalBackground, verticalBackground, staticBackground, cgScroll]) assert.match(background, /@swipe="blockSystemBack"/)
  for (const layer of ['stageSingleImage', 'stageDuoLeftImage', 'stageDuoRightImage', 'stageTrioLeftImage', 'stageTrioCenterImage', 'stageTrioRightImage', 'stageOverlayImage']) {
    assert.ok(template.includes(`src="{{${layer}}}" if="{{${layer} && !isFullScreenCg}}"`))
  }
  assert.match(detail, /\.page \{ width: 336px; height: 480px;[^}]*overflow: hidden;/)
  assert.match(detail, /\.background-scroll \{[^}]*width: 336px;[^}]*height: 480px;/)
  assert.match(detail, /\.background-vertical-scroll \{[^}]*width: 336px;[^}]*height: 480px;/)
  assert.match(detail, /\.cg-scroll \{[^}]*width: 336px;[^}]*height: 480px;/)
  for (const selector of ['background', 'background-horizontal', 'background-vertical', 'cg-image']) assert.match(detail, new RegExp(`\\.${selector} \\{[^}]*width: 692px;[^}]*height: 520px;`))
  assert.match(detail, /\.dialogue-panel \{[^}]*top: 306px;[^}]*left: 0px;[^}]*width: 336px;[^}]*height: 174px;[^}]*background-color: #120d13;[^}]*opacity: 0\.30;/)
  assert.match(detail, /\.character-name \{[^}]*top: 312px;[^}]*left: 18px;[^}]*width: 300px;/)
  assert.match(detail, /\.scroll \{[^}]*top: 342px;[^}]*left: 12px;[^}]*width: 312px;[^}]*height: 130px;/)
  assert.match(detail, /\.top-right-overlay \{[^}]*top: 76px;[^}]*left: 70px;[^}]*width: 100px;[^}]*height: 60px;/)
  assert.match(detail, /\.menu-trigger-hit \{[^}]*left: 74px;[^}]*width: 64px;[^}]*height: 64px;/)
  assert.match(detail, /chapterLabel: '第1章'/)
  assert.match(detail, /sceneProgress: '场景 1'/)
})

test('renders choice options as compact vertically centered buttons', () => {
  const template = detail.slice(0, detail.indexOf('</template>'))

  assert.doesNotMatch(template, /class="choice-title"/)
  assert.match(template, /<scroll scroll-y="true" bounces="true" class="choice-list">\s*<div class="choice-grid">\s*<text class="choice" for="\{\{choices\}\}" @click="selectChoice\(\$idx\)">\{\{\$item\.text\}\}<\/text>/)
  assert.match(detail, /\.choice-list \{[^}]*top: 64px;[^}]*left: 24px;[^}]*width: 288px;[^}]*height: 352px;/)
  assert.match(detail, /\.choice-grid \{[^}]*width: 288px;[^}]*min-height: 352px;[^}]*flex-direction: column;[^}]*flex-wrap: nowrap;[^}]*justify-content: center;[^}]*align-items: center;/)
  assert.match(detail, /\.choice \{[^}]*width: 264px;[^}]*height: 56px;[^}]*font-size: 18px;[^}]*line-height: 23px;/)
  assert.match(detail, /selectChoice\(choiceIndex\)/)
})

test('uses one scroll-clipped horizontal background for the 10 Pro', () => {
  const template = detail.slice(0, detail.indexOf('</template>'))
  assert.match(template, /<scroll id="bg-horizontal-scroll" scroll-x="true" scroll-y="false" bounces="false" class="background-scroll" if="\{\{Img && backgroundMode === 'horizontal'\}\}" @swipe="blockSystemBack">/)
  assert.match(template, /<image class="background-horizontal" src="\{\{Img\}\}"><\/image>/)
  assert.doesNotMatch(template, /bg-horizontal-(?:pill|rect)/)
  assert.match(detail, /if \(motion === 'horizontal'\) return this\.startHorizontalBackgroundMotion\(token\)/)
  assert.match(template, /<scroll id="bg-vertical-scroll" scroll-x="false" scroll-y="true" bounces="false" class="background-vertical-scroll"/)
  assert.match(template, /<div class="background-vertical-track"><image class="background-vertical" src="\{\{Img\}\}"><\/image><\/div>/)
  assert.match(detail, /return this\.startVerticalBackgroundMotion\(token\)/)
  assert.match(detail, /const travel = 48/)
  assert.match(detail, /this\.scrollBackground\('bg-vertical-scroll', 0, top\)/)
  assert.match(detail, /scrollBackground\(id, left, top\)/)
  assert.match(detail, /const travel = 356/)
  assert.match(detail, /scrollTo\(\{ top: 0, left: 178, behavior: 'instant' \}\)/)
  assert.match(detail, /const duration = 5000/)
  assert.match(detail, /this\.scrollBackground\('bg-horizontal-scroll', left, 0\)/)
  assert.match(detail, /backgroundTimer: null/)
  assert.match(detail, /typingTimer: null/)
  assert.match(detail, /cgCenterTimer: null/)
  assert.match(detail, /clearTimeout\(this\.backgroundTimer\)/)
  assert.match(detail, /clearTimeout\(this\.typingTimer\)/)
  assert.match(detail, /clearTimeout\(this\.cgCenterTimer\)/)
  assert.doesNotMatch(detail, /@media \(shape: rect\)|height: 303px/)
})

test('uses a full-screen menu and preserves performant reader behavior', () => {
  const template = detail.slice(0, detail.indexOf('</template>'))
  const horizontalBackground = template.match(/<scroll id="bg-horizontal-scroll"[^>]*>/)[0]
  const verticalBackground = template.match(/<scroll id="bg-vertical-scroll"[^>]*>/)[0]
  const staticBackground = template.match(/<image id="bg-static"[^>]*>/)[0]
  const cgScroll = template.match(/<scroll id="cg-scroll"[^>]*>/)[0]
  const cgImage = template.match(/<image class="cg-image"[^>]*>/)[0]
  assert.match(template, /<div class="page menu-page" if="\{\{menu\}\}" @swipe="back">/)
  assert.match(template, /<div class="menu-status">[\s\S]*class="chapter-label"[\s\S]*class="scene-progress"/)
  assert.match(template, /@click="openSavePage"/)
  assert.match(template, /@click="openLoadPage"/)
  assert.match(template, /@click="openSettingsPage"/)
  assert.doesNotMatch(template, /openAboutPage/)
  assert.match(detail, /\.menu-page \{[^}]*top: 0px;[^}]*left: 0px;[^}]*background-color: #171119;/)
  assert.match(detail, /openSavePage\(\)[\s\S]*?key: 'pendingSave'/)
  assert.match(detail, /openLoadPage\(\) \{ this\.menu = false; router\.push\(\{ uri: 'pages\/saves', params: \{ mode: 'load' \} \}\) \}/)
  assert.match(detail, /openSettingsPage\(\) \{ this\.menu = false; router\.push\(\{ uri: 'pages\/settings' \}\) \}/)
  assert.match(detail, /\.menu-page \{[^}]*justify-content: center;/)
  assert.match(detail, /\.menu-close \{[^}]*width: 184px;[^}]*height: 50px;[^}]*background-color: #302b33;[^}]*border-radius: 10px;/)
  assert.match(detail, /if \(!this\.canContinue\) return this\.finishTyping\(\)/)
  assert.match(detail, /if \(this\.settings\.textSpeed === 0\) \{\s*this\.finishTyping\(\)\s*if \(countForAutoSave\) this\.recordAutoSaveDialogue\(\)\s*return\s*\}/)
  assert.match(detail, /prefetchNextChunk\(sceneIndex\)/)
  assert.match(detail, /trimChunkCache\(sceneIndex\)/)
  assert.match(detail, /loadSettings\(\) \{\s*storage\.get\(\{ key: 'settings'/)
  for (const background of [horizontalBackground, verticalBackground, staticBackground, cgScroll, cgImage]) assert.doesNotMatch(background, /background-(?:horizontal|vertical)-motion/)
  assert.doesNotMatch(detail, /import folme from '@system\.folme'|folme\./)
  assert.match(detail, /backgroundMotionToken: 0/)
  assert.match(detail, /startBackgroundMotion\(motion\)/)
  assert.match(detail, /startHorizontalBackgroundMotion\(token\)/)
  assert.match(detail, /startVerticalBackgroundMotion\(token\)/)
  assert.match(detail, /const travel = 48/)
  assert.match(detail, /scrollBackground\('bg-vertical-scroll', 0, top\)/)
  assert.match(detail, /if \(this\.destroyed \|\| token !== this\.backgroundMotionToken\) return/)
  assert.match(detail, /if \(!isCg && \(motion === 'horizontal' \|\| motion === 'vertical'\)\) this\.startBackgroundMotion\(motion\)/)
  assert.match(detail, /if \(this\.isCg \|\| !this\.Img \|\| !this\.backgroundMode\) return/)
  assert.match(detail, /if \(this\.Img === image && this\.backgroundMode === motion && this\.isCg === isCg && this\.isFullScreenCg === isFullScreenCg\) return/)
  assert.match(detail, /onHide\(\) \{[^}]*this\.stopBackgroundMotion\(\); this\.flushAutoSave\(\); this\.clearAutoPlayTimer\(\) \}/)
  assert.match(detail, /onDestroy\(\) \{[^}]*this\.stopBackgroundMotion\(\); this\.flushAutoSave\(\); this\.clearAutoPlayTimer\(\);/)
  assert.doesNotMatch(detail, /animation-name|animation-duration|animation-iteration-count|@keyframes/)
  assert.match(detail, /blockSystemBack\(\) \{\}/)
  assert.match(detail, /nextSafeChapter\(\)/)
})

test('uses the moved date overlay slot for every calendar scene', () => {
  const keys = []
  const chunkDir = path.join('src', 'common', 'story', 'chunks')
  for (const file of fs.readdirSync(chunkDir)) {
    for (const scene of JSON.parse(fs.readFileSync(path.join(chunkDir, file), 'utf8'))) {
      if (scene.topRightOverlay) keys.push(scene.topRightOverlay.key)
    }
  }
  assert.equal(keys.length, 10)
  assert.ok(keys.every((key) => /^日历/.test(key)))
})
